services:
  minecraft:
    image: itzg/minecraft-server #Imagen de Docker a utilizar
    container_name: mc-crossplay #Nombre del contenedor
    ports: #Puertos a mapear
      - "25565:25565/tcp"
      - "19132:19132/udp"
    environment: #Variables de entorno
      EULA: "TRUE"
      TYPE: "PAPER" #Tipo de servidor
      VERSION: "LATEST" #Version del servidor
      MEMORY: "4G" #Memoria RAM asignada al servidor
      ONLINE_MODE: "false" #Desactivar modo online (para piratas)
      PLUGINS: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
      MODRINTH_PROJECTS: "viaversion,viabackwards"
    volumes: #Volumes a mapear
      - ./data:/data #Volumen para persistencia de datos
    restart: unless-stopped #Reiniciar el contenedor a menos que se detenga manualmente
